apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Chart.Name}}-jellyfin-config
spec:
  storageClassName: {{.Values.storage.config.storageClass}}
  accessModes:
    {{- .Values.storage.config.accessModes | toYaml | nindent 4}}
  resources:
    requests:
      storage: {{.Values.storage.config.size}}