apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name}}
spec:
  selector:
    app: jellyfin
  ports:
    - protocol: TCP
      port: {{.Values.service.port}}
      targetPort: 8096
  type: {{.Values.service.type}}
  